'\" te
.TH rpmmacros 5 "01 Jan 2017" "RTPrpmmacros" "File Formats"

.nh
.ad b
.SH NAME
.PP
rpmmacros - macro definitions for building runtime platform RPM packages

.SH DESCRIPTION
.PP
In addition to being compiled to build packages in the \fI/usr/src/\fR
directory, the redhat package manager also reads \fI/etc/rpmmacros\fR and
\fI$HOME/.rpmmacros\fR file, and will override, as well as augment built-in
macro definitions with the ones found in the above files.
.PP
This repository contains the macro overrides of the rpm built-ins, as well as
additional macro definitions required to build all runtime platform RPM packages
with the \fBrpmbuild(1)\fR command. The \fI.rpmmacros\fR file can be copied
either to one's home, or to the \fI/etc/\fR directory as \fI/etc/rpmmacros\fR.

.SH SEE ALSO
.PP
\fBrpmbuild(1)\fR, \fBintro(5)\fR.

































































